// Isolated only. Never connects to Supabase or production.
// Requires a SELECT-only inspection fixture and a temporary @electric-sql/pglite installation.
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import vm from "node:vm";
import { createRequire } from "node:module";
const root = path.resolve(import.meta.dirname, "..");
const fixturePath = process.env.SETTINGS_INSPECTION_FIXTURE;
assert(fixturePath, "Set SETTINGS_INSPECTION_FIXTURE to the read-only captured fixture");
const fixture = JSON.parse(fs.readFileSync(fixturePath, "utf8").replace(/^\uFEFF/, "")).rows[0].fixture;
const { PGlite } = await import(process.env.PGLITE_MODULE
  ? pathToFileURL(process.env.PGLITE_MODULE).href : "@electric-sql/pglite");
const migration = fs.readFileSync(path.join(root, "supabase/migrations/20261004000400_settings_permission_modules.sql"), "utf8");
const service = fs.readFileSync(path.join(root, "src/services/settingsService.js"), "utf8");
const contracts = {
  update_settings_profile: ["p_full_name"], assign_settings_user_role: ["p_user_id", "p_role_id"],
  create_settings_role: ["p_name", "p_description"], delete_settings_role: ["p_role_id"],
  save_settings_role_permissions: ["p_role_id", "p_permissions"],
};
let passed = 0;
const pass = (label) => { passed += 1; console.log(`PASS ${label}`); };
for (const [name, params] of Object.entries(contracts)) {
  const signature = migration.match(new RegExp(`CREATE FUNCTION public\\.${name}\\(([^)]*)\\)`));
  assert(signature, name);
  assert.deepEqual(signature[1].split(",").map((part) => part.trim().split(/\s+/)[0]), params);
  const call = service.match(new RegExp(`supabase\\.rpc\\("${name}",\\s*\\{([^}]+)\\}`));
  assert(call, name);
  assert.deepEqual([...call[1].matchAll(/(p_\w+)\s*:/g)].map((match) => match[1]), params);
}
pass("all five exact RPC/service parameter contracts");
assert(!/\.from\("(?:roles|profiles|role_permissions)"\)\s*\.(?:update|insert|delete)/.test(service));
pass("service uses guarded RPCs for database mutations");
const q = (text) => `'${String(text).replaceAll("'", "''")}'`;
const uid = (n) => `00000000-0000-0000-0000-${String(n).padStart(12, "0")}`;
const setup = async () => {
  const db = new PGlite();
  await db.exec(`CREATE ROLE authenticated; CREATE ROLE anon; CREATE SCHEMA auth;
    CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
    GRANT USAGE ON SCHEMA auth TO authenticated,anon;
    CREATE TABLE profiles(id uuid PRIMARY KEY,full_name text,email text,role_id bigint,is_active boolean DEFAULT true,
      must_change_password boolean DEFAULT false);
    CREATE TABLE system_settings(id bigint PRIMARY KEY,setting_key text,setting_value jsonb,updated_by uuid);
    CREATE TABLE products(id uuid PRIMARY KEY,product_code text UNIQUE,product_type text,category text,base_unit text,is_active boolean);
    CREATE TABLE recipes(id uuid PRIMARY KEY,product_id uuid,yield_unit text);
    CREATE TABLE recipe_ingredients(id uuid PRIMARY KEY,product_id uuid,recipe_id uuid,unit text);
    CREATE TABLE audit_logs(id bigint PRIMARY KEY,module_name text,entity_code text,entity_id text,metadata jsonb);
    CREATE SEQUENCE product_type_allocation_seq;
    CREATE SEQUENCE raw_material_seq START 11; CREATE SEQUENCE semi_finished_seq START 7;
    CREATE SEQUENCE finished_product_seq START 10; CREATE SEQUENCE packaging_seq START 2;`);
  for (const table of ["roles", "role_permissions", "product_master_values"]) {
    const columns = fixture.columns.filter((column) => column.table === table);
    const ddl = columns.map((c) => `"${c.name}" ${c.type}${c.identity ? " GENERATED BY DEFAULT AS IDENTITY" : c.default ? ` DEFAULT ${c.default}` : ""}${c.notnull ? " NOT NULL" : ""}`).join(",");
    await db.exec(`CREATE TABLE ${table}(${ddl});`);
  }
  await db.exec(`ALTER TABLE roles ADD PRIMARY KEY(id); ALTER TABLE role_permissions ADD PRIMARY KEY(id);
    ALTER TABLE role_permissions ADD CONSTRAINT role_permissions_unique_module UNIQUE(role_id,module_name);
    ALTER TABLE role_permissions ADD FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE;
    ALTER TABLE role_permissions ADD CONSTRAINT role_permissions_print_modules_check CHECK(NOT can_print OR lower(btrim(module_name)) IN ('reports','audit trail'));
    ALTER TABLE profiles ADD FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE SET NULL;
    ALTER TABLE product_master_values ADD PRIMARY KEY(id); ALTER TABLE product_master_values ADD UNIQUE(type_key);
    ALTER TABLE product_master_values ADD UNIQUE(code_prefix); ALTER TABLE product_master_values ADD UNIQUE(type_allocation);
    CREATE UNIQUE INDEX master_value_unique ON product_master_values(kind,lower(value));
    ALTER TABLE products ADD FOREIGN KEY(product_type) REFERENCES product_master_values(type_key) ON UPDATE RESTRICT ON DELETE RESTRICT;`);
  for (const [table, rows] of [["roles", fixture.roles], ["role_permissions", fixture.permissions]]) {
    const columns = fixture.columns.filter((c) => c.table === table).map((c) => `"${c.name}"`).join(",");
    await db.exec(`INSERT INTO ${table}(${columns}) SELECT ${columns} FROM jsonb_populate_recordset(NULL::${table},${q(JSON.stringify(rows))}::jsonb);`);
  }
  await db.exec(`SELECT setval(pg_get_serial_sequence('roles','id'),100,true);
    SELECT setval(pg_get_serial_sequence('role_permissions','id'),100,true);
    INSERT INTO profiles(id,full_name,email,role_id) VALUES
      ('${uid(1)}','Administrator','admin@example.invalid',1),('${uid(4)}','Delegate','delegate@example.invalid',4),
      ('${uid(7)}','ERP','erp@example.invalid',7),('${uid(8)}','Viewer','viewer@example.invalid',8);
    INSERT INTO product_master_values(kind,value,type_key,arabic_name,allows_ingredient,allows_recipe_product,is_system_type,code_prefix) VALUES
      ('product_type','Raw Material','Raw Material','مادة خام',true,false,true,'RM'),
      ('product_type','Semi-Finished','Semi-Finished','منتج نصف مصنع',true,true,true,'SF'),
      ('product_type','Finished Product','Finished Product','منتج نهائي',false,true,true,'FP'),
      ('product_type','Packaging','Packaging','تغليف',true,false,true,'PK');
    INSERT INTO product_master_values(kind,value) VALUES('category','Flour'),('unit','Kg'),('unit','Piece');
    INSERT INTO products VALUES('${uid(100)}','RM-0001','Raw Material','Flour','Kg',false);
    INSERT INTO recipes VALUES('${uid(101)}','${uid(100)}','Piece');
    INSERT INTO recipe_ingredients VALUES('${uid(102)}','${uid(100)}','${uid(101)}','Kg');`);
  for (const entry of fixture.functions) await db.exec(entry.definition);
  await db.exec(`CREATE TRIGGER product_type_metadata_guard BEFORE UPDATE OR DELETE ON product_master_values
    FOR EACH ROW EXECUTE FUNCTION guard_product_type_metadata();`);
  for (const table of ["roles", "role_permissions", "profiles", "product_master_values", "system_settings"]) {
    await db.exec(`ALTER TABLE ${table} ENABLE ROW LEVEL SECURITY; GRANT SELECT,INSERT,UPDATE,DELETE ON ${table} TO authenticated;`);
  }
  for (const p of fixture.policies) {
    await db.exec(`CREATE POLICY "${p.policyname}" ON ${p.tablename} AS ${p.permissive} FOR ${p.cmd} TO ${p.roles.join(",")}${p.qual ? ` USING (${p.qual})` : ""}${p.with_check ? ` WITH CHECK (${p.with_check})` : ""};`);
  }
  return db;
};
const snapshot = async (db) => (await db.query(`SELECT jsonb_build_object(
  'legacy',(SELECT jsonb_agg(to_jsonb(p) ORDER BY id) FROM role_permissions p WHERE module_name NOT IN ('General Settings','Permissions & User Rights','Master Data')),
  'roles',(SELECT jsonb_agg(to_jsonb(r) ORDER BY id) FROM roles r),
  'profiles',(SELECT jsonb_agg(to_jsonb(p) ORDER BY id) FROM profiles p),
  'products',(SELECT jsonb_agg(to_jsonb(p) ORDER BY id) FROM products p),
  'recipes',(SELECT jsonb_agg(to_jsonb(p) ORDER BY id) FROM recipes p),
  'ingredients',(SELECT jsonb_agg(to_jsonb(p) ORDER BY id) FROM recipe_ingredients p),
  'masters',(SELECT jsonb_agg(to_jsonb(p) ORDER BY id) FROM product_master_values p),
  'sequences',(SELECT jsonb_agg(jsonb_build_array(sequencename,last_value) ORDER BY sequencename) FROM pg_sequences WHERE sequencename IN ('raw_material_seq','semi_finished_seq','finished_product_seq','packaging_seq','product_type_allocation_seq'))
) AS result`)).rows[0].result;
const db = await setup();
const before = await snapshot(db);

await db.exec(migration);
assert.deepEqual(await snapshot(db), before);
pass("real migration commits with unchanged legacy/application/metadata rows and canonical/allocation sequences");
assert.equal((await db.query(`SELECT count(*)::int AS n FROM role_permissions WHERE module_name IN ('General Settings','Permissions & User Rights','Master Data') AND NOT(can_view OR can_add OR can_edit OR can_delete OR can_print)`)).rows[0].n,12);
pass("exactly 12 approved non-admin rows OFF; no administrator replication");
const runAs = async (id, sql, params = []) => {
  await db.exec("RESET ROLE");
  await db.query("SELECT set_config('request.jwt.claim.sub',$1,false)",[id]);
  await db.exec("SET ROLE authenticated");
  try { return await db.query(sql,params); } finally { await db.exec("RESET ROLE"); }
};
const deny = async (id, sql, params, expected = /settings_permission/) => {
  await assert.rejects(runAs(id,sql,params),expected);
};
const flags = async (module, view, add=true, edit=true, del=true) => db.query(`UPDATE role_permissions SET can_view=$1,can_add=$2,can_edit=$3,can_delete=$4 WHERE role_id=4 AND module_name=$5`,[view,add,edit,del,module]);
await flags("General Settings",false,false,true,false);
await deny(uid(4),"SELECT update_settings_profile($1)",["Changed"]);
await flags("Permissions & User Rights",false);
for (const [sql,params] of [["SELECT create_settings_role($1,$2)",["Blocked",""]],
  ["SELECT assign_settings_user_role($1,$2)",[uid(7),4]], ["SELECT delete_settings_role($1)",[5]],
  ["SELECT save_settings_role_permissions($1,$2)",[7,"[]"]]]) await deny(uid(4),sql,params);
await flags("Master Data",false);
await deny(uid(4),"SELECT manage_product_master_value('add','category',NULL,'Blocked')",[],/master_values_permission/);
await deny(uid(4),"SELECT manage_product_type('add',NULL,'Blocked','ممنوع',true,true)",[],/product_type_permission/);
pass("View OFF + action ON denied for all five new RPCs and both master-data RPCs");
await flags("General Settings",true,false,true,false);
const priorProfile = (await db.query("SELECT * FROM profiles WHERE id=$1",[uid(4)])).rows[0];
await runAs(uid(4),"SELECT update_settings_profile($1)",["  Updated Delegate  "]);
const updated = (await db.query("SELECT * FROM profiles WHERE id=$1",[uid(4)])).rows[0];
assert.deepEqual(updated,{...priorProfile,full_name:"Updated Delegate"});
assert.equal((await db.query("SELECT full_name FROM profiles WHERE id=$1",[uid(1)])).rows[0].full_name,"Administrator");
await deny(uid(4),"SELECT update_settings_profile($1)",["  "],/Full name/);
pass("General Settings changes only caller full_name, trims it, rejects blanks");
await runAs(uid(4),"UPDATE profiles SET role_id=1 WHERE id=$1",[uid(4)]);
assert.equal((await db.query("SELECT role_id FROM profiles WHERE id=$1",[uid(4)])).rows[0].role_id,4);
pass("direct delegated profile UPDATE cannot promote caller");
await flags("Permissions & User Rights",true);
await deny(uid(4),"SELECT assign_settings_user_role($1,$2)",[uid(4),1],/settings_protected_admin/);
await deny(uid(4),"SELECT assign_settings_user_role($1,$2)",[uid(1),4],/settings_protected_admin/);
await deny(uid(4),"SELECT save_settings_role_permissions($1,$2)",[1,"[]"],/settings_protected_admin/);
await deny(uid(4),"SELECT delete_settings_role($1)",[1],/settings_protected_admin/);
pass("delegated administrator promotion, account assignment, role permission modification and deletion blocked");
const role = (await runAs(uid(4),"SELECT * FROM create_settings_role($1,$2)",["Local Test Role","Local only"])).rows[0];
assert.equal(role.is_system_admin,false);
await runAs(uid(4),"SELECT assign_settings_user_role($1,$2)",[uid(7),role.id]);
await deny(uid(4),"SELECT delete_settings_role($1)",[role.id],/users are assigned/);
await runAs(uid(4),"SELECT assign_settings_user_role($1,$2)",[uid(7),7]);
await runAs(uid(4),"SELECT delete_settings_role($1)",[role.id]);
pass("delegated ordinary role create/assignment/delete work; assigned-role deletion stays blocked");
const row = {role_id:7,module_name:"Master Data",can_view:false,can_add:true,can_edit:true,can_delete:true,can_print:false};
await runAs(uid(4),"SELECT save_settings_role_permissions($1,$2)",[7,JSON.stringify([row])]);
await deny(uid(7),"SELECT manage_product_master_value('add','unit',NULL,'Blocked')",[],/master_values_permission/);
assert.deepEqual((await snapshot(db)).legacy,before.legacy);
await deny(uid(4),"SELECT save_settings_role_permissions($1,$2)",[7,JSON.stringify([{...row,module_name:"Settings"}])],/Invalid permission module/);
await deny(uid(4),"SELECT save_settings_role_permissions($1,$2)",[7,JSON.stringify([{...row,module_name:"Users / Role"}])],/Invalid permission module/);
await deny(uid(4),"SELECT save_settings_role_permissions($1,$2)",[7,JSON.stringify([{...row,can_print:true}])],/Unsupported Print/);
await deny(uid(4),"SELECT save_settings_role_permissions($1,$2)",[7,JSON.stringify([{...row,module_name:"General Settings"}])],/only View and Edit/);
const oldPermissions=(await db.query("SELECT jsonb_agg(to_jsonb(r)) AS v FROM role_permissions r")).rows[0].v;
await deny(uid(4),"SELECT save_settings_role_permissions($1,$2)",[7,JSON.stringify([row,{...row,module_name:"Unsupported"}])],/Invalid permission module/);
assert.deepEqual((await db.query("SELECT jsonb_agg(to_jsonb(r)) AS v FROM role_permissions r")).rows[0].v,oldPermissions);
pass("atomic permission save, independent flags, unsupported actions/Print and legacy submissions protected");
// Existing consumer metadata clauses stay independent of Master Data View.
for (const module of ["Product Master","Recipes","Dashboard","Reports","Audit Trail","ERP Entry"]) {
  await db.query("UPDATE role_permissions SET can_view=false,can_add=false,can_edit=false,can_delete=false WHERE role_id=8");
  await db.query(`INSERT INTO role_permissions(role_id,module_name,can_view) VALUES(8,$1,true)
    ON CONFLICT(role_id,module_name) DO UPDATE SET can_view=true`,[module]);
  const types=(await runAs(uid(8),"SELECT type_key FROM product_master_values WHERE kind='product_type'")).rows;
  assert.equal(types.length,4,module);
  if(module==="Product Master") assert.equal((await runAs(uid(8),"SELECT * FROM product_master_values WHERE kind IN ('category','unit')")).rows.length,3);
}
pass("all six consumer modules retain required metadata without Master Data View");
await flags("Master Data",true);
for(const kind of ["category","unit"]) {
  const value=(await runAs(uid(4),"SELECT * FROM manage_product_master_value('add',$1,NULL,$2)",[kind,`Unused ${kind}`])).rows[0];
  const renamed=(await runAs(uid(4),"SELECT * FROM manage_product_master_value('rename',$1,$2,$3,$4)",[kind,value.id,`Renamed ${kind}`,value.updated_at])).rows[0];
  await runAs(uid(4),"SELECT manage_product_master_value('delete',$1,$2,NULL,$3)",[kind,renamed.id,renamed.updated_at]);
}
for(const name of ["Flour","Kg","Piece"]) {
  const item=(await db.query("SELECT * FROM product_master_values WHERE value=$1",[name])).rows[0];
  await deny(uid(4),"SELECT manage_product_master_value('delete',$1,$2,NULL,$3)",[item.kind,item.id,item.updated_at],/master_values_in_use/);
  await deny(uid(4),"SELECT manage_product_master_value('rename',$1,$2,'Changed',$3)",[item.kind,item.id,item.updated_at],/master_values_in_use/);
}
pass("Category/Unit CRUD, inactive-Product usage and Recipe/Ingredient Unit safeguards preserved");
const type=(await db.query("SELECT * FROM product_master_values WHERE type_key='Raw Material'")).rows[0];
await deny(uid(4),"SELECT manage_product_type('delete',$1,NULL,NULL,NULL,NULL,$2)",[type.id,type.updated_at],/product_type_protected/);
await deny(uid(4),"SELECT manage_product_type('edit',$1,$2,$3,false,false,$4)",[type.id,type.value,type.arabic_name,type.updated_at],/product_type_ingredient_in_use/);
pass("canonical Product Type deletion and ingredient-eligibility protections unchanged");
await runAs(uid(1),"SELECT update_settings_profile($1)",["Admin updated"]);
await runAs(uid(1),"SELECT save_settings_role_permissions($1,$2)",[1,"[]"]);
assert.equal((await runAs(uid(1),"SELECT has_module_permission('Master Data','delete') AS allowed")).rows[0].allowed,true);
pass("system-admin override works without new-module rows");
await db.close();
// Fail-safe migration rollback on unexpected target rows.
const bad=await setup();
await bad.exec("INSERT INTO role_permissions(role_id,module_name,can_view) VALUES(4,'Master Data',true)");
const badBefore=await snapshot(bad);
await assert.rejects(bad.exec(migration),/Unexpected target permission rows/);
await bad.exec("ROLLBACK");
assert.deepEqual(await snapshot(bad),badBefore);
assert.equal((await bad.query("SELECT count(*)::int AS n FROM pg_proc WHERE proname='update_settings_profile'")).rows[0].n,0);
pass("unexpected target state aborts transaction with no partial RPC or row changes");
await bad.close();
// Execute real deployed-function code with local mocks; no HTTP/database calls.
const require=createRequire(path.join(path.dirname(fixturePath),"package.json"));
const ts=require("typescript");
const edgeSource=fs.readFileSync(path.join(root,"supabase/functions/manage-user-index-ts/index.ts"),"utf8")
  .replace(/import\s*\{\s*createClient,?\s*\}\s*from\s*"npm:@supabase\/supabase-js@2";/,"const createClient = globalThis.mockCreateClient;");
const transpiled=ts.transpileModule(edgeSource,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;
const edgeCase=async ({admin=false,view=true,actionPermission=true,targetAdmin=false,roleAdmin=false,action="create"}) => {
  const writes=[]; let handler;
  const query=(table)=>{
    let id; const chain={select(){return chain;},eq(_key,value){id=value;return chain;},ilike(){id="duplicate";return chain;},
      async maybeSingle(){return {error:null,data:table==="roles"?{id:1,is_system_admin:roleAdmin}:id===uid(4)?
        {id,is_active:true,roles:{is_system_admin:admin}}:id==="duplicate"?null:{id,roles:{is_system_admin:targetAdmin}}};},
      async upsert(value){writes.push(["upsert",value]);return {error:null};},update(value){writes.push(["update",value]);return chain;},
      delete(){writes.push(["delete-profile"]);return chain;},then(resolve){resolve({error:null});}}; return chain;
  };
  const caller={auth:{async getUser(){return {data:{user:{id:uid(4)}},error:null};}},async rpc(_name,args){return {data:args.p_action==="view"?view:actionPermission,error:null};}};
  const adminClient={from:query,auth:{admin:{async createUser(value){writes.push(["create",value]);return {data:{user:{id:uid(9)}},error:null};},
    async updateUserById(id,value){writes.push(["password",id,value]);return {error:null};},async deleteUser(id){writes.push(["delete-auth",id]);return {error:null};}}}};
  vm.runInNewContext(transpiled,{globalThis:{mockCreateClient:(_url,key)=>key==="SUPABASE_ANON_KEY"?caller:adminClient},
    Deno:{env:{get:key=>key},serve:fn=>{handler=fn;}},Response,console});
  const response=await handler({method:"POST",headers:new Headers({Authorization:"Bearer local-test"}),json:async()=>({action,
    fullName:"Local",username:"local",password:"abcdef",roleId:1,userId:uid(7)})});
  return {status:response.status,writes};
};
for(const action of ["create","reset-password","delete"]) {
  assert.deepEqual(await edgeCase({action,view:false}),{status:403,writes:[]});
  assert.deepEqual(await edgeCase({action,actionPermission:false}),{status:403,writes:[]});
  assert.equal((await edgeCase({action})).status,200);
  assert.equal((await edgeCase({action,admin:true,view:false,actionPermission:false,targetAdmin:true,roleAdmin:true})).status,200);
}
assert.deepEqual(await edgeCase({roleAdmin:true}),{status:403,writes:[]});
for(const action of ["reset-password","delete"]) assert.deepEqual(await edgeCase({action,targetAdmin:true}),{status:403,writes:[]});
pass("real Edge source: delegated View/action enforcement, protected admins and admin override");
// Actual permission-table helper behavior and source guards, including all tab combinations.
const settings=fs.readFileSync(path.join(root,"src/pages/Settings.jsx"),"utf8");
const helpers=settings.slice(settings.indexOf("const modules ="),settings.indexOf("function Settings()"));
const context={}; vm.runInNewContext(helpers+";globalThis.permissions=createPermissions(true);",context);
assert.deepEqual(Object.keys(context.permissions["General Settings"]),["view","edit"]);
for(const module of ["General Settings","Permissions & User Rights","Master Data"]) assert(!("print" in context.permissions[module]));
for(let mask=0;mask<8;mask++) {
  const profile={is_active:true,roles:{is_system_admin:false},permissions:Object.fromEntries(["General Settings","Permissions & User Rights","Master Data"]
    .map((m,index)=>[m.toLowerCase(),{view:Boolean(mask&(1<<index)),add:true,edit:true,delete:true}]))};
  context.p=profile;
  const allowed=vm.runInNewContext('["General Settings","Permissions & User Rights","Master Data"].filter(m=>refreshedAllows(p,m))',context);
  assert.equal(allowed.length,[0,1,2].filter(i=>mask&(1<<i)).length);
}
assert(settings.includes('window.addEventListener("focus", focus)'));
assert(settings.includes('document.addEventListener("visibilitychange", visible)'));
assert(!/setInterval|postgres_changes/.test(settings));
assert(settings.includes('if (!currentRequest()) return;'));
assert(settings.includes('beforeAction={(action) => authorizeAction("Master Data"'));
assert(!/hasPermission\("Settings"|hasAnyPermission\(\["Settings"/.test(settings));
const i18n=fs.readFileSync(path.join(root,"src/i18n.js"),"utf8");
assert(i18n.includes('accounts: "Permissions & User Rights"')&&i18n.includes('accounts: "الصلاحيات وحقوق المستخدمين"'));
pass("all tab combinations, supported actions, bilingual labels, event refresh and stale-request source checks");

// Render the actual Settings component with local service/auth mocks.
const React=require("react");
const renderer=require("react-test-renderer");
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const {act}=renderer;
const authContext=React.createContext(null);
const authCalls=[];
let refreshResult,updateAuth;
const refreshProfile=async()=>{authCalls.push("refresh");updateAuth(refreshResult);return refreshResult;};
const makeProfile=(flags,admin=false)=>({id:uid(4),role_id:4,is_active:true,full_name:"Local User",email:"local@example.invalid",
  roles:{is_system_admin:admin},permissions:Object.fromEntries(Object.entries(flags).map(([m,v])=>[m.toLowerCase(),
    typeof v==="boolean"?{view:v,add:v,edit:v,delete:v}:v]))});
const windowEvents=new Map(),documentEvents=new Map();
const fakeWindow={addEventListener:(name,fn)=>windowEvents.set(name,fn),removeEventListener:(name,fn)=>{if(windowEvents.get(name)===fn)windowEvents.delete(name);}};
const fakeDocument={visibilityState:"visible",activeElement:null,body:{},
  addEventListener:(name,fn)=>documentEvents.set(name,fn),removeEventListener:(name,fn)=>{if(documentEvents.get(name)===fn)documentEvents.delete(name);}};
let lang="en",accountLoads=0,masterLoads=0,profileWrites=0,masterWrites=0;
let accountLoader=async()=>({roles:[{id:4,name:"Approver",isSystemAdmin:false,removable:true}],
  employees:[{id:uid(4),name:"Local User",username:"local",roleId:4,isSystemAdmin:false}],permissions:[]});
const serviceMocks={getSettingsData:async()=>{accountLoads++;return accountLoader();},updateCurrentProfile:async()=>{profileWrites++;},
  createRole:async()=>({id:9,name:"Local Role"}),createUser:async()=>({}),deleteRole:async()=>true,deleteUser:async()=>true,
  resetUserPassword:async()=>true,saveRolePermissions:async()=>true,updateEmployeeRole:async()=>true};
const values=[{id:uid(200),kind:"category",value:"Local Category",is_active:true,updated_at:"2026-10-04"}];
const valueMocks={getProductMasterValues:async()=>{masterLoads++;return values;},manageProductMasterValue:async(_action,kind,_item,value)=>{
  masterWrites++;return {id:uid(201),kind,value};},productMasterValueError:()=>"error"};
const translations={en:{"settingsPage.tabs.general":"General Settings","settingsPage.tabs.permissions":"Permissions & User Rights",
  "settingsPage.masterData.title":"Master Data"},ar:{"settingsPage.tabs.general":"الإعدادات العامة",
  "settingsPage.tabs.permissions":"الصلاحيات وحقوق المستخدمين","settingsPage.masterData.title":"البيانات الأساسية"}};
const translate=(key)=>translations[lang][key]||key;
const translation={t:translate,i18n:{language:"en",changeLanguage:async(value)=>{lang=value;}}};
const useAuth=()=>{const p=React.useContext(authContext);return {profile:p,user:{id:p.id},loading:false,refreshProfile,isAdmin:Boolean(p.roles?.is_system_admin),
  hasAnyPermission:(modules,action="view")=>modules.some(module=>Boolean(p.roles?.is_system_admin||p.permissions[module.toLowerCase()]?.[action])),signOut:async()=>({success:true}),
  hasPermission:(module,action="view")=>Boolean(p.roles?.is_system_admin||p.permissions[module.toLowerCase()]?.[action])};};
const icons=new Proxy({},{get:(_target,key)=>key==="__esModule"?false:()=>React.createElement("span",{"data-icon":String(key)})});
const mocks={react:React,"react/jsx-runtime":require("react/jsx-runtime"),"lucide-react":icons,
  "react-dom":{createPortal:(child)=>child},"react-i18next":{useTranslation:()=>translation},
  "../context/AuthContext":{useAuth},"../services/settingsService":serviceMocks,"../services/productMasterValuesService":valueMocks,
  "../services/productTypesService":{manageProductType:async()=>({}),productTypeError:()=>"error"},
  "../context/ProductTypesContext":{useProductTypes:()=>({types:[],label:key=>key,changed:()=>{},ready:true,loading:false,error:null})},
  "../components/ProductTypesReadiness":{default:()=>null}};
const compile=(file)=>{
  const source=fs.readFileSync(path.join(root,file),"utf8");
  const js=ts.transpileModule(source,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
  const module={exports:{}};
  vm.runInNewContext(js,{module,exports:module.exports,require:(id)=>id.endsWith(".css")?{}:mocks[id]||(()=>{throw new Error(`Unmocked ${id}`);})(),
    window:fakeWindow,document:fakeDocument,console,alert:()=>{},setTimeout,clearTimeout});
  return module.exports.default;
};
mocks["../components/ManageProductMasterValuesModal"]={default:compile("src/components/ManageProductMasterValuesModal.jsx")};
mocks["../components/ManageProductTypeModal"]={default:compile("src/components/ManageProductTypeModal.jsx")};
const SettingsComponent=compile("src/pages/Settings.jsx");
const Provider=({initial})=>{const [p,setP]=React.useState(initial);updateAuth=setP;return React.createElement(authContext.Provider,{value:p},React.createElement(SettingsComponent));};
const mount=async(profile)=>{
  refreshResult=profile;let tree;
  await act(async()=>{tree=renderer.create(React.createElement(Provider,{initial:profile}));});
  return tree;
};
const text=(node)=>JSON.stringify(node.toJSON());
const tabLabels=(tree)=>tree.root.findByProps({className:"settings-tabs"}).findAllByType("button").map(b=>b.children.join(""));
for(lang of ["en","ar"]) {
  translation.i18n.language=lang;
  for(let mask=1;mask<8;mask++) {
    const modules=["General Settings","Permissions & User Rights","Master Data"];
    const profile=makeProfile(Object.fromEntries(modules.map((module,i)=>[module,{view:Boolean(mask&(1<<i)),add:false,edit:false,delete:false}])));
    const loadsBefore=accountLoads;
    const tree=await mount(profile);
    assert.deepEqual(tabLabels(tree),modules.filter((_m,i)=>mask&(1<<i)).map(m=>translations[lang][
      m==="General Settings"?"settingsPage.tabs.general":m==="Permissions & User Rights"?"settingsPage.tabs.permissions":"settingsPage.masterData.title"]));
    assert.equal(accountLoads>loadsBefore,Boolean(mask&2));
    assert.equal(tree.root.findByProps({className:"settings-tabs"}).findAllByType("button")[0].props.className,"active");
    if(mask&1) assert.equal(tree.root.findByProps({name:"fullName"}).props.disabled,true);
    await act(async()=>tree.unmount());
  }
}
pass("actual Settings render: all seven accessible tab combinations/default order in English/Arabic; no unauthorized account loads");
lang="en";translation.i18n.language="en";
let tree=await mount(makeProfile({"General Settings":{view:true,edit:true}}));
refreshResult=makeProfile({"General Settings":{view:true,edit:false}});
await act(async()=>tree.root.findByProps({className:"general-save-button"}).props.onClick());
assert.equal(profileWrites,0);
assert.equal(tree.root.findByProps({name:"fullName"}).props.disabled,true);
await act(async()=>tree.unmount());
pass("actual General save refresh prevents a write after Edit revocation");
// An in-flight employee response must not repopulate state after access changes.
let resolveOld;
accountLoader=()=>new Promise(resolve=>{resolveOld=resolve;});
tree=await mount(makeProfile({"Permissions & User Rights":true,"Master Data":true}));
refreshResult=makeProfile({"Master Data":true});
await act(async()=>windowEvents.get("focus")());
assert.deepEqual(tabLabels(tree),["Master Data"]);
accountLoader=async()=>({roles:[{id:4,name:"Approver",isSystemAdmin:false,removable:true}],
  employees:[{id:uid(4),name:"Fresh Employee",username:"fresh",roleId:4}],permissions:[]});
refreshResult=makeProfile({"Permissions & User Rights":true});
await act(async()=>documentEvents.get("visibilitychange")());
await act(async()=>resolveOld({roles:[],employees:[{id:uid(9),name:"STALE SENSITIVE EMPLOYEE",username:"stale"}],permissions:[]}));
assert(!text(tree).includes("STALE SENSITIVE EMPLOYEE"));
assert(text(tree).includes("Fresh Employee"));
await act(async()=>tree.unmount());
pass("actual focus/visibility refresh switches tabs and ignores stale sensitive employee responses");
// Exercise the actual reusable modal's submit refresh and permission-loss close.
tree=await mount(makeProfile({"Master Data":true}));
const addButton=tree.root.findAllByType("button").find(b=>b.children.includes("settingsPage.masterData.addCategory"));
assert(addButton);
await act(async()=>addButton.props.onClick());
await act(async()=>tree.root.findByProps({id:"product-value-name"}).props.onChange({target:{value:"New Local Category"}}));
refreshResult=makeProfile({"Master Data":{view:true,add:false,edit:true,delete:true}});
const form=tree.root.findAllByType("form")[0];
await act(async()=>form.props.onSubmit({preventDefault(){}}));
assert.equal(masterWrites,0);
assert.equal(tree.root.findAllByProps({id:"product-value-name"}).length,0);
await act(async()=>tree.unmount());
pass("actual Category modal refresh blocks revoked Add and closes unauthorized modal");


// Render the actual navigation and route guard, including all Views OFF.
mocks["../../context/AuthContext"]={useAuth};
mocks["react-router-dom"]={useLocation:()=>({pathname:"/settings"}),useNavigate:()=>()=>{},
  Navigate:({to})=>React.createElement("div",{"data-redirect":to}),Outlet:()=>React.createElement("div",{"data-outlet":true})};
mocks["../assets/images/bites-brand.png"]={default:"local-logo.png"};
const RouteGuard=compile("src/components/auth/ProtectedRoute.jsx");
const SidebarComponent=compile("src/components/Sidebar.jsx");
const routeModules=["General Settings","Permissions & User Rights","Master Data"];
for(let mask=0;mask<8;mask++) {
  const p=makeProfile(Object.fromEntries(routeModules.map((module,i)=>[module,{view:Boolean(mask&(1<<i)),add:true,edit:true,delete:true}])));
  // Legacy flags must not grant access when all new Views are OFF.
  p.permissions.settings={view:true,add:true,edit:true,delete:true};p.permissions["users / role"]={view:true,add:true,edit:true,delete:true};
  let nav,route;
  await act(async()=>{
    nav=renderer.create(React.createElement(authContext.Provider,{value:p},React.createElement(SidebarComponent)));
    route=renderer.create(React.createElement(authContext.Provider,{value:p},React.createElement(RouteGuard,{anyOfModules:routeModules})));
  });
  assert.equal(nav.root.findAllByProps({className:"sidebar-menu"})[0].findAllByType("button").length,mask?1:0);
  assert.equal(route.root.findAllByProps({"data-outlet":true}).length,mask?1:0);
  if(!mask)assert(text(route).includes("Access Denied"));
  await act(async()=>{nav.unmount();route.unmount();});
}
pass("actual route/navigation: every View combination, one Settings item, legacy flags never unlock access");
// Existing matching OFF target rows must be retained rather than overwritten.
const existingOff=await setup();
await existingOff.exec("INSERT INTO role_permissions(role_id,module_name) VALUES(4,'Master Data')");
const retained=(await existingOff.query("SELECT to_jsonb(r) AS row FROM role_permissions r WHERE role_id=4 AND module_name='Master Data'")).rows[0].row;
await existingOff.exec(migration);
assert.deepEqual((await existingOff.query("SELECT to_jsonb(r) AS row FROM role_permissions r WHERE role_id=4 AND module_name='Master Data'")).rows[0].row,retained);
await existingOff.close();
pass("migration preserves a pre-existing approved OFF target row byte-for-byte");

console.log(`${passed} verification groups PASS; production connections/writes: zero.`);
