name: Supabase Keep Alive

on:
  schedule:
    - cron: "0 8 * * *"

  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Supabase Edge Function
        run: |
          curl -f https://lxljoolqvukyngvajxga.supabase.co/functions/v1/keep-alive
